import { shuffleWithSeed } from "@/lib/anagram-indicators";
import { listArchivedInspirations } from "@/lib/db/clue-archive";
import { anthropicChatJson, parseModelJson } from "@/lib/llm";
import { setterModel } from "@/lib/models";
import type { ClaudeCallTrace } from "@/lib/types";

export const AUTO_INSPIRATION_SYSTEM =
  "You suggest fun crossword puzzle themes. Reply with JSON only — no markdown.";

/** Fallback themes with plenty of anagram-friendly names and words. */
const CURATED_FUN_THEMES = [
  "Mortal Kombat characters",
  "Batman villains and allies",
  "Studio Ghibli films",
  "Harry Potter spells and characters",
  "Star Wars droids and pilots",
  "Marvel Avengers roster",
  "Classic detective fiction",
  "British birds and garden wildlife",
  "Jazz legends and instruments",
  "Coffee, tea and café culture",
  "Olympic sports and events",
  "Shakespeare plays and characters",
  "Greek mythology heroes",
  "Norse gods and sagas",
  "Chess openings and pieces",
  "Board games and card games",
  "Vintage cars and marques",
  "London landmarks and boroughs",
  "French cuisine and ingredients",
  "Italian opera and composers",
  "James Bond gadgets and villains",
  "Doctor Who companions",
  "Pixar movie characters",
  "Nintendo heroes and items",
  "Pokémon types and trainers",
  "Lord of the Rings places",
  "Sherlock Holmes cases",
  "Agatha Christie detectives",
  "Broadway musicals",
  "Rock and roll hall of fame",
  "Famous painters and art movements",
  "Botany and flowers",
  "Dogs, cats and pets",
  "Weather and the seasons",
  "Pirates and the high seas",
  "Medieval knights and castles",
  "Egyptian pharaohs and gods",
  "Space exploration and planets",
  "Chemistry elements and lab gear",
  "Gardening tools and plants",
] as const;

/** Pick a theme at random — archived and curated themes may repeat across runs. */
export function pickFallbackTheme(seed = `${Date.now()}`): string {
  const archived = listArchivedInspirations();
  const pool = [...new Set([...CURATED_FUN_THEMES, ...archived])];
  const shuffled = shuffleWithSeed(pool, seed);
  return shuffled[0] ?? `Surprise theme ${seed.slice(-6)}`;
}

function buildThemePrompt(previousThemes: string[]): string {
  const usedBlock =
    previousThemes.length > 0
      ? previousThemes.map((t) => `- ${t}`).join("\n")
      : "(none yet — pick anything lively)";

  return `Suggest exactly ONE fun, vivid inspiration theme for a British cryptic anagram puzzle.

REQUIREMENTS
1. A short phrase (3–12 words) that names a clear topic — films, characters, hobbies, places, food, sport, etc.
2. Must be genuinely fun and specific enough for themed answers (e.g. "Studio Ghibli films", not just "movies").
3. Reusing a theme from previous runs is allowed — you may pick from the list below or revisit a similar topic.
4. Prefer themes with many proper names or concrete nouns that can form anagrams.

THEMES FROM PREVIOUS RUNS (reuse is fine):
${usedBlock}

Return ONLY valid JSON:
{ "inspiration": "Your theme phrase" }`;
}

async function suggestThemeWithClaude(
  apiKey: string,
  previousThemes: string[]
): Promise<{ theme: string; trace: ClaudeCallTrace } | null> {
  const user = buildThemePrompt(previousThemes);
  try {
    const content = await anthropicChatJson({
      apiKey,
      model: setterModel(),
      system: AUTO_INSPIRATION_SYSTEM,
      user,
      maxTokens: 256,
      timeoutMs: 25_000,
    });

    const parsed = parseModelJson<{ inspiration?: string }>(content);
    const theme = parsed.inspiration?.trim();
    if (!theme || theme.length < 4 || theme.length > 160) return null;
    return {
      theme,
      trace: {
        order: 1,
        label: "Auto theme suggestion",
        system: AUTO_INSPIRATION_SYSTEM,
        user,
        response: content,
      },
    };
  } catch {
    return null;
  }
}

export interface ResolveInspirationResult {
  inspiration: string;
  autoGenerated: boolean;
  /** 1 when auto-theme used a successful Claude call; otherwise 0. */
  claudeCallsSucceeded: number;
  autoThemeTrace?: ClaudeCallTrace;
}

/**
 * Use the user's theme when provided; otherwise pick a fun theme
 * (may reuse inspirations from earlier runs or the archive).
 */
export async function resolveInspiration(
  apiKey: string,
  raw: string
): Promise<ResolveInspirationResult> {
  const trimmed = raw.trim();
  if (trimmed) {
    return { inspiration: trimmed, autoGenerated: false, claudeCallsSucceeded: 0 };
  }

  const previousThemes = listArchivedInspirations();
  const suggested = await suggestThemeWithClaude(apiKey, previousThemes);
  if (suggested) {
    return {
      inspiration: suggested.theme,
      autoGenerated: true,
      claudeCallsSucceeded: 1,
      autoThemeTrace: suggested.trace,
    };
  }

  return {
    inspiration: pickFallbackTheme(),
    autoGenerated: true,
    claudeCallsSucceeded: 0,
  };
}

