/**
 * Curated setter-style hints for homophone clue surfaces.
 * Short (1–3 words), British English, crossword-appropriate — never the literal word.
 */

const HOMOPHONE_CURATED_HINTS: Readonly<Record<string, readonly string[]>> = {
  // Money & commerce
  cash: ["bread", "dough", "money", "notes"],
  cache: ["bin", "store", "hoard", "stash"],
  cachet: ["stamp", "prestige", "seal"],
  cent: ["penny", "coin"],
  scent: ["aroma", "perfume", "smell"],
  sent: ["posted", "dispatched", "mailed"],
  sell: ["trade", "vend", "flog"],
  cell: ["prison", "cage", "chamber"],
  bin: ["container", "tank", "skip"],
  been: ["existed", "visited"],
  bun: ["roll", "bap", "cake"],

  // Food & drink
  meat: ["grub", "flesh", "food"],
  meet: ["greet", "encounter", "convene"],
  mete: ["dole", "apportion", "allot"],
  steak: ["cut", "beef", "fillet"],
  stake: ["post", "wager", "share"],
  flour: ["powder", "milling"],
  flower: ["bloom", "blossom", "petal"],
  bread: ["loaf", "dough", "bakery"],
  bred: ["reared", "raised", "nurtured"],
  pear: ["fruit", "pomaceous"],
  pair: ["couple", "duo", "twosome"],
  pare: ["trim", "peel", "shave"],
  pea: ["legume", "pulse"],
  piece: ["bit", "fragment", "portion"],
  peace: ["tranquillity", "calm", "harmony"],
  cereal: ["breakfast", "grain", "cornflakes"],
  serial: ["series", "sequence", "ongoing"],
  sweet: ["dessert", "sugary", "confection"],
  suite: ["rooms", "apartment", "furniture"],
  tea: ["brew", "char", "cuppa"],
  tee: ["peg", "golf"],
  thyme: ["herb", "seasoning"],
  time: ["hour", "moment", "era"],
  beet: ["root", "vegetable"],
  beat: ["rhythm", "pulsate", "thrash"],
  leek: ["vegetable", "allium"],
  leak: ["seep", "drip", "escape"],
  maize: ["corn", "grain"],
  maze: ["labyrinth", "puzzle"],
  currant: ["berry", "dried fruit"],
  current: ["flow", "present"],
  desert: ["arid", "abandon", "wasteland"],
  dessert: ["pudding", "sweet", "afters"],
  dough: ["mix", "money", "paste"],
  doe: ["hind", "female deer"],
  dew: ["moisture", "condensation"],
  due: ["owing", "expected", "scheduled"],

  // Common cryptic pairs
  knight: ["horseman", "cavalier", "noble"],
  night: ["dark", "evening", "bedtime"],
  colonel: ["officer", "rank"],
  kernel: ["core", "heart", "nut"],
  handsome: ["attractive", "good-looking", "comely"],
  hansom: ["cab", "carriage", "hackney"],
  allowed: ["permitted", "legal", "sanctioned"],
  aloud: ["audibly", "verbally", "orally"],
  write: ["pen", "scribe", "jot"],
  right: ["correct", "proper", "lawful"],
  rite: ["ceremony", "ritual", "service"],
  wright: ["maker", "builder", "craftsman"],
  bare: ["naked", "stark", "unadorned"],
  bear: ["bruin", "carry", "tolerate"],
  break: ["fracture", "pause", "smash"],
  brake: ["curb", "retard", "slow"],
  hole: ["gap", "cavity", "opening"],
  whole: ["entire", "complete", "total"],
  sea: ["ocean", "waves", "brine"],
  see: ["behold", "spot", "witness"],
  sun: ["solar", "daystar"],
  son: ["boy", "offspring", "lad"],
  sonny: ["lad", "youngster"],
  sunny: ["bright", "clear", "radiant"],
  one: ["single", "unity"],
  won: ["prevailed", "triumphed"],
  two: ["pair", "couple"],
  too: ["also", "overly", "excessively"],
  to: ["towards", "direction"],
  heard: ["listened", "overheard"],
  herd: ["flock", "drove", "cattle"],
  hear: ["listen", "overhear"],
  here: ["present", "spot"],
  their: ["possessive", "belonging"],
  there: ["yonder", "place"],
  theyre: ["contraction", "abbreviation"],

  // Homophones A–B
  abbe: ["priest", "cleric"],
  abbey: ["monastery", "cloister"],
  addition: ["sum", "extra"],
  edition: ["issue", "version", "imprint"],
  adieu: ["farewell", "goodbye"],
  ado: ["fuss", "commotion"],
  affect: ["influence", "impact"],
  effect: ["result", "outcome"],
  ail: ["trouble", "afflict"],
  ale: ["beer", "bitter"],
  altar: ["shrine", "chancel"],
  alter: ["change", "modify", "amend"],
  ant: ["insect", "colony"],
  aunt: ["relative", "kinswoman"],
  arc: ["curve", "bow"],
  ark: ["vessel", "boat"],
  are: ["exist", "equal"],
  our: ["possessive", "belonging"],
  err: ["mistake", "blunder"],
  heir: ["successor", "inheritor"],
  air: ["atmosphere", "breeze"],
  ere: ["before", "prior"],
  aisle: ["passage", "gangway"],
  isle: ["island"],
  ill: ["sick", "unwell"],
  ascent: ["climb", "rise", "mount"],
  assent: ["agree", "consent", "approve"],
  auger: ["drill", "bore"],
  augur: ["portend", "foretell"],
  aye: ["yes", "affirmative"],
  eye: ["sight", "orb"],
  ball: ["sphere", "dance", "orb"],
  bawl: ["weep", "wail", "howl"],
  balm: ["salve", "ointment"],
  bomb: ["explosive", "device"],
  band: ["group", "strip"],
  banned: ["prohibited", "barred"],
  bar: ["pub", "rod"],
  baron: ["noble", "peer"],
  barren: ["sterile", "empty"],
  base: ["bottom", "foundation"],
  bass: ["fish", "deep"],
  bay: ["inlet", "howl"],
  bey: ["governor", "ruler"],
  beach: ["shore", "sands"],
  beech: ["tree", "timber"],
  bell: ["chime", "ring"],
  belle: ["beauty", "belle"],
  below: ["under", "beneath"],
  billow: ["surge", "swell"],
  bite: ["nibble", "chomp"],
  byte: ["data", "digit"],
  bight: ["bay", "loop"],
  bloc: ["alliance", "group"],
  block: ["obstacle", "cube"],
  blue: ["sad", "azure"],
  blew: ["puffed", "gusted"],
  bow: ["bend", "ribbon"],
  beau: ["suitor", "lover"],
  bough: ["branch", "limb"],
  buy: ["purchase", "acquire"],
  bye: ["farewell", "absent"],
  bowled: ["delivered", "hurled"],
  bole: ["trunk", "stem"],
  boar: ["pig", "swine", "hog"],
  bowl: ["dish", "container"],
  bridal: ["wedding", "nuptial"],
  bridle: ["rein", "curb"],
  broach: ["raise", "introduce"],
  brooch: ["pin", "badge"],
  bur: ["prickle", "seed"],
  burr: ["burr", "rough edge"],

  // C–F
  callous: ["hardened", "uncaring"],
  callus: ["thick skin", "hard patch"],
  calm: ["peaceful", "serene", "still"],
  com: ["company", "firm"],
  comm: ["army", "signal", "radio"],
  cannon: ["artillery", "gun"],
  canon: ["rule", "standard"],
  canvas: ["sailcloth", "fabric"],
  canvass: ["survey", "poll"],
  capital: ["funds", "city"],
  capitol: ["legislature", "building"],
  carrot: ["root", "vegetable"],
  carat: ["measure", "karat"],
  caster: ["wheel", "roller"],
  castor: ["oil", "beaver"],
  cedar: ["tree", "timber"],
  cede: ["yield", "surrender"],
  seed: ["grain", "sow"],
  censer: ["incense", "burner"],
  censor: ["suppress", "ban"],
  sensor: ["detector", "probe"],
  chalk: ["white stick", "mark"],
  chock: ["wedge", "block"],
  chord: ["music", "harmony"],
  cord: ["rope", "string"],
  choral: ["sung", "choir"],
  coral: ["reef", "polyps"],
  chic: ["stylish", "elegant"],
  sheikh: ["ruler", "emir"],
  cite: ["quote", "mention"],
  sight: ["view", "vision"],
  site: ["location", "venue"],
  clause: ["provision", "term"],
  claws: ["talons", "nails"],
  coal: ["fuel", "ember"],
  coarse: ["rough", "crude"],
  course: ["route", "path", "meal"],
  council: ["committee", "assembly"],
  counsel: ["advice", "barrister"],
  cue: ["signal", "prompt"],
  queue: ["line", "wait"],
  creek: ["stream", "brook"],
  creak: ["groan", "squeak"],
  cruel: ["harsh", "brutal"],
  crewel: ["wool", "embroidery"],
  cymbal: ["percussion", "brass"],
  symbol: ["sign", "emblem"],
  dam: ["barrier", "block"],
  damn: ["curse", "condemn"],
  dear: ["beloved", "costly"],
  deer: ["stag", "hart"],
  discreet: ["tactful", "careful"],
  discrete: ["separate", "distinct"],
  die: ["expire", "perish"],
  dye: ["colour", "tint"],
  doc: ["physician", "medic"],
  dock: ["pier", "wharf"],
  done: ["finished", "complete"],
  dun: ["grey", "dun-coloured"],
  dual: ["double", "twin"],
  duel: ["combat", "contest"],
  earn: ["merit", "deserve"],
  urn: ["vase", "vessel"],
  fair: ["just", "exhibition", "blonde"],
  fare: ["price", "ticket", "food"],
  fairy: ["sprite", "fae"],
  ferry: ["boat", "crossing"],
  fate: ["destiny", "lot"],
  fete: ["festival", "celebration"],
  feat: ["deed", "achievement"],
  feet: ["toes", "plural foot"],
  fir: ["tree", "evergreen"],
  fur: ["pelt", "coat"],
  for: ["towards", "purpose"],
  flea: ["parasite", "insect"],
  flee: ["escape", "run"],
  flew: ["soared", "travelled"],
  flu: ["influenza", "virus"],
  floe: ["iceberg", "ice"],
  flow: ["stream", "current"],
  foul: ["rank", "dirty", "offside"],
  fowl: ["bird", "poultry"],
  franc: ["currency", "coin"],
  frank: ["candid", "direct"],
  freeze: ["ice", "chill"],
  frieze: ["band", "ornament"],
  friar: ["monk", "brother"],
  fryer: ["cooker", "pan"],

  // G–L
  gait: ["walk", "stride"],
  gate: ["entrance", "barrier"],
  gel: ["jelly", "set"],
  jell: ["set", "solidify"],
  get: ["obtain", "fetch"],
  git: ["fool", "idiot"],
  gild: ["gold", "adorn"],
  guild: ["society", "union"],
  gilt: ["gold", "coated"],
  guilt: ["shame", "blame"],
  gnu: ["antelope", "wildebeest"],
  knew: ["aware", "realised"],
  new: ["fresh", "novel"],
  grate: ["irritate", "grating"],
  great: ["grand", "superb"],
  groan: ["moan", "lament"],
  grown: ["matured", "developed"],
  hail: ["greet", "pellets"],
  hale: ["healthy", "robust"],
  hair: ["locks", "tresses"],
  hare: ["leveret", "rabbit"],
  hall: ["corridor", "vestibule"],
  haul: ["drag", "pull", "heave"],
  heal: ["cure", "mend"],
  heel: ["cad", "rascal"],
  hell: ["inferno", "underworld"],
  hangar: ["shed", "shelter"],
  hanger: ["hook", "rail"],
  hoard: ["stash", "treasure"],
  horde: ["mob", "crowd", "throng"],
  hoarse: ["rasping", "husky"],
  horse: ["mount", "steed"],
  hour: ["sixty minutes"],
  holy: ["sacred", "devout"],
  wholly: ["entirely", "fully"],
  hostel: ["lodging", "inn"],
  hostile: ["unfriendly", "aggressive"],
  idle: ["lazy", "inactive"],
  idol: ["icon", "hero"],
  idyll: ["pastoral", "idyll"],
  inc: ["company", "firm"],
  ink: ["fluid", "dye"],
  jam: ["preserve", "squeeze"],
  jamb: ["frame", "post"],
  karat: ["measure", "purity"],
  knead: ["work dough", "massage"],
  need: ["require", "want"],
  knee: ["joint", "leg"],
  nee: ["born", "maiden"],
  knot: ["tie", "tangle"],
  not: ["negation"],
  knit: ["stitch", "unite"],
  nit: ["egg", "louse"],
  know: ["understand", "realise"],
  no: ["negation"],
  lain: ["reclined", "rested"],
  lane: ["path", "alley"],
  lass: ["girl", "lassie"],
  last: ["final", "endure"],
  lead: ["guide", "metal"],
  led: ["guided", "conducted"],
  leaf: ["foliage", "page"],
  lief: ["gladly", "willing"],
  lean: ["thin", "tilt"],
  lien: ["claim", "charge"],
  leach: ["drain", "seep"],
  leech: ["parasite", "drain"],
  lessen: ["reduce", "diminish"],
  lesson: ["class", "tutorial"],
  levee: ["embankment", "dam"],
  levy: ["tax", "impose"],
  licence: ["permit", "authority"],
  license: ["permit", "authorise"],
  light: ["bright", "illumination"],
  lite: ["low-cal", "reduced"],
  limb: ["arm", "branch"],
  limn: ["depict", "portray"],
  load: ["burden", "cargo"],
  lode: ["vein", "deposit"],
  loan: ["advance", "lending"],
  lone: ["solitary", "single"],
  loot: ["plunder", "booty"],
  lute: ["instrument", "lute"],
  loo: ["lavatory", "toilet"],
  lieu: ["stead", "place"],

  // M–R
  mail: ["post", "armour"],
  male: ["masculine", "man"],
  main: ["chief", "principal"],
  mane: ["hair", "locks"],
  mall: ["shopping", "centre"],
  maul: ["claw", "mangle"],
  marry: ["wed", "unite"],
  merry: ["jolly", "cheerful"],
  marshal: ["organise", "officer"],
  martial: ["military", "warlike"],
  marten: ["weasel", "animal"],
  martin: ["bird", "swallow"],
  mat: ["rug", "pad"],
  matt: ["dull", "flat"],
  matte: ["dull", "finish"],
  medal: ["award", "honour"],
  meddle: ["interfere", "pry"],
  metal: ["iron", "alloy"],
  mettle: ["spirit", "pluck"],
  miner: ["digger", "collier"],
  minor: ["lesser", "young"],
  missed: ["overlooked", "absent"],
  mist: ["fog", "haze"],
  midst: ["middle", "centre"],
  moat: ["ditch", "trench"],
  mote: ["speck", "particle"],
  morning: ["dawn", "daybreak"],
  mourning: ["grief", "lament"],
  moose: ["elk"],
  mousse: ["dessert", "foam"],
  muscle: ["brawn", "strength"],
  mussel: ["shellfish", "bivalve"],
  naval: ["maritime", "seagoing"],
  navel: ["bellybutton", "umbilicus"],
  none: ["zero", "nil"],
  nun: ["sister", "religious"],
  oar: ["paddle", "blade"],
  ore: ["mineral", "metal"],
  oral: ["spoken", "verbal"],
  aural: ["heard", "auditory"],
  pale: ["wan", "light"],
  pail: ["bucket", "container"],
  pain: ["ache", "hurt"],
  pane: ["glass", "window"],
  peak: ["summit", "top"],
  peek: ["glance", "peep"],
  pique: ["irritate", "interest"],
  peal: ["ring", "chime"],
  peel: ["skin", "rind"],
  peer: ["equal", "noble"],
  pier: ["jetty", "wharf"],
  plain: ["simple", "flatland"],
  plane: ["flat", "aircraft"],
  plait: ["braid", "twist"],
  plate: ["dish", "slab"],
  plum: ["fruit", "choice"],
  plumb: ["vertical", "exact"],
  pole: ["rod", "extremity"],
  poll: ["vote", "survey"],
  pore: ["study", "opening"],
  pour: ["decant", "stream"],
  pray: ["beg", "supplicate"],
  prey: ["quarry", "victim"],
  principal: ["head", "chief"],
  principle: ["tenet", "rule"],
  profit: ["gain", "margin"],
  prophet: ["seer", "oracle"],
  rain: ["shower", "downpour"],
  reign: ["rule", "sovereignty"],
  rein: ["bridle", "curb"],
  read: ["peruse", "scan"],
  red: ["crimson", "scarlet"],
  real: ["genuine", "actual"],
  reel: ["spool", "stagger"],
  rest: ["repose", "remainder"],
  wrest: ["wrench", "force"],
  ring: ["circle", "call"],
  wring: ["squeeze", "twist"],
  role: ["part", "function"],
  roll: ["bun", "rotate"],
  root: ["base", "origin"],
  route: ["path", "way"],
  rough: ["coarse", "uneven"],
  ruff: ["collar", "frill"],
  rye: ["grain", "cereal"],
  wry: ["ironic", "twisted"],
  rap: ["knock", "music"],
  wrap: ["cover", "enfold"],
  rapper: ["MC", "lyricist"],
  wrapper: ["cover", "packaging"],
  rapt: ["engrossed", "ecstatic"],
  raise: ["lift", "rear"],
  raze: ["demolish", "destroy"],
  rack: ["torture", "shelf"],
  wrack: ["wreck", "ruin"],
  rho: ["letter", "Greek"],
  roe: ["fish eggs", "caviar"],
  row: ["line", "argument"],

  // S–Z
  sail: ["voyage", "canvas"],
  sale: ["bargain", "auction"],
  scene: ["view", "setting"],
  seen: ["viewed", "spotted"],
  seam: ["joint", "stitch"],
  seem: ["appear", "look"],
  sew: ["stitch", "needle"],
  sow: ["plant", "scatter"],
  shear: ["clip", "cut"],
  sheer: ["pure", "steep"],
  slay: ["kill", "murder"],
  sleigh: ["sledge", "runners"],
  sleight: ["dexterity", "trickery"],
  slight: ["snub", "minor"],
  soar: ["rise", "tower"],
  sore: ["painful", "tender"],
  some: ["a few", "several"],
  sum: ["total", "addition"],
  steal: ["pilfer", "thieve"],
  steel: ["metal", "iron"],
  straight: ["direct", "unbent"],
  strait: ["narrow", "channel"],
  tail: ["rear", "appendage"],
  tale: ["story", "yarn"],
  team: ["squad", "side"],
  teem: ["swarm", "abound"],
  taught: ["educated", "instructed"],
  taut: ["tight", "tense"],
  threw: ["hurled", "cast"],
  through: ["via", "across"],
  throne: ["seat", "sovereignty"],
  thrown: ["hurled", "cast"],
  toe: ["digit", "tip"],
  tow: ["haul", "drag"],
  ton: ["weight"],
  tonne: ["metric ton"],
  wear: ["don", "clothing"],
  where: ["place", "location"],
  ware: ["goods", "merchandise"],
  weak: ["feeble", "frail"],
  week: ["seven days"],
  wait: ["delay", "stay"],
  weight: ["heaviness", "load"],
  waist: ["middle", "midriff"],
  waste: ["rubbish", "squander"],
  weather: ["climate", "forecast"],
  whether: ["if"],
  which: ["that"],
  witch: ["hag", "sorceress"],
  wood: ["timber", "lumber"],
  would: ["might", "could"],
  wail: ["cry", "lament"],
  whale: ["cetacean", "leviathan"],
  walk: ["stroll", "pace"],
  wok: ["pan", "cooker"],
  wave: ["gesture", "ripple"],
  waive: ["relinquish", "forgo"],
  way: ["path", "route"],
  weigh: ["measure", "balance"],
  whey: ["curds", "by-product"],
  well: ["healthy", "spring"],
  wheel: ["tyre", "disc"],
  will: ["testament", "intention"],
  win: ["triumph", "prevail"],
  when: ["time", "moment"],
  wine: ["vintage", "claret"],
  whine: ["moan", "complain"],
  while: ["whilst", "during"],
  wile: ["trick", "ruse"],
  white: ["pale", "colour"],
  wight: ["creature", "being"],
  wit: ["humour", "cleverness"],
  whit: ["jot", "iota"],
  woe: ["grief", "sorrow"],
  whoa: ["stop", "halt"],
  hoe: ["tool", "dig"],
  yew: ["tree", "evergreen"],
  ewe: ["sheep", "lamb"],
  you: ["yourself", "addressee"],
  vale: ["valley", "dale"],
  veil: ["cover", "shroud"],
  vain: ["conceited", "futile"],
  vane: ["weathercock", "blade"],
  vein: ["blood vessel", "seam"],
  vice: ["deputy", "fault"],
  vise: ["clamp", "grip"],
  wack: ["blow", "hit"],
  whack: ["strike", "blow"],
  wary: ["cautious", "careful"],
  wherry: ["boat", "skiff"],
  worst: ["least", "defeated"],
  wurst: ["sausage", "banger"],
};

function normalizeWord(word: string): string {
  return word.toLowerCase().replace(/[^a-z]/g, "");
}

function capitalizeHint(hint: string): string {
  const trimmed = hint.trim();
  if (!trimmed) return trimmed;
  return trimmed.charAt(0).toUpperCase() + trimmed.slice(1);
}

function isUsableCuratedHint(hint: string, word: string): boolean {
  const normalizedHint = hint.toLowerCase().replace(/[^a-z\s]/g, "").trim();
  const normalizedWord = word.toLowerCase().replace(/[^a-z]/g, "");
  if (!normalizedHint || normalizedHint.length < 2) return false;
  if (normalizedHint === normalizedWord) return false;
  if (new RegExp(`\\b${normalizedWord}\\b`, "i").test(normalizedHint)) return false;
  const wordCount = normalizedHint.split(/\s+/).filter(Boolean).length;
  if (wordCount > 3) return false;
  return true;
}

/** Curated setter-style hints for a homophone word, if available. */
export function getCuratedHomophoneHints(word: string): string[] {
  const key = normalizeWord(word);
  if (!key) return [];

  const raw = HOMOPHONE_CURATED_HINTS[key];
  if (!raw?.length) return [];

  const seen = new Set<string>();
  const hints: string[] = [];

  for (const hint of raw) {
    if (!isUsableCuratedHint(hint, key)) continue;
    const capitalized = capitalizeHint(hint);
    const dedupeKey = capitalized.toLowerCase();
    if (seen.has(dedupeKey)) continue;
    seen.add(dedupeKey);
    hints.push(capitalized);
  }

  return hints;
}

/** Whether curated hints exist for this word. */
export function hasCuratedHomophoneHints(word: string): boolean {
  return getCuratedHomophoneHints(word).length > 0;
}
