import { NextRequest, NextResponse } from "next/server";
import { resolveInspiration } from "@/lib/auto-inspiration";
import { generateVerifiedAnagramClue } from "@/lib/anagram-pipeline";
import { requireUser } from "@/lib/auth/require-user";
import {
  consumeGenerationCredit,
  getCreditsStatus,
} from "@/lib/db/users";
import type { AnagramRequest } from "@/lib/types";

export const maxDuration = 180;

export async function POST(request: NextRequest) {
  try {
    const auth = await requireUser();
    if ("response" in auth) return auth.response;

    const creditsBefore = getCreditsStatus(auth.user);
    if (!creditsBefore.canGenerate) {
      return NextResponse.json(
        {
          error: "No credits remaining. Add credits to generate more clues.",
          credits: creditsBefore,
        },
        { status: 402 }
      );
    }

    const body = (await request.json()) as { request: AnagramRequest };

    const apiKey = process.env.ANTHROPIC_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "No Anthropic API key. Set ANTHROPIC_API_KEY in .env.local." },
        { status: 401 }
      );
    }

    const { inspiration, autoGenerated, claudeCallsSucceeded } =
      await resolveInspiration(apiKey, body.request?.inspiration ?? "");

    const req: AnagramRequest = {
      inspiration,
      difficulty:
        body.request?.difficulty === "hard" ? "hard" : "easy",
      exclude: body.request?.exclude,
    };

    const outcome = await generateVerifiedAnagramClue(apiKey, req, {
      autoThemed: autoGenerated,
    });

    if ("error" in outcome) {
      return NextResponse.json({ error: outcome.error }, { status: 422 });
    }

    const successfulClaudeCalls = outcome.llmCalls + claudeCallsSucceeded;
    const credits =
      successfulClaudeCalls > 0
        ? consumeGenerationCredit(auth.user.id)
        : creditsBefore;

    return NextResponse.json({ result: outcome, credits });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Generation failed";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
